# fly.toml app configuration file generated for {{cookiecutter.project_slug}}
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = '{{ cookiecutter.project_slug.replace("_", "-") }}'
primary_region = 'ams'

[build]
  dockerfile = 'docker/Dockerfile'

[http_service]
  internal_port = {% if cookiecutter.app_type == 'fastapi' %}8008{% else %}8888{% endif %}
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
{% if "nats" in cookiecutter.app_type %}
[[services]]
  http_checks = []
  internal_port = 8000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    type = "connections"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 8000{%- endif %}{% if "fastapi" in cookiecutter.app_type %}
[[services]]
  http_checks = []
  internal_port = 8008
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    type = "connections"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 8008{%- endif %}{% if "mesop" in cookiecutter.app_type %}
[[services]]
  http_checks = []
  internal_port = 8888
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    type = "connections"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 8888{%- endif %}
