# fly.toml app configuration file generated for {{cookiecutter.project_slug}} on {% now 'local', '%Y-%m-%dT%H:%M:%SZ' %}
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = '{{cookiecutter.project_slug}}_{{ random_ascii_string(10) }}'
primary_region = 'ams'

[build]
  dockerfile = 'docker/Dockerfile'

[http_service]
  internal_port = 8888
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
