version: '3'

services:
  python-{{cookiecutter.python_version}}-{{cookiecutter.project_slug}}:
    image: mcr.microsoft.com/devcontainers/python:{{cookiecutter.python_version}}
    container_name: {{cookiecutter.project_slug}}-${USER}-python-{{cookiecutter.python_version}}
    volumes:
      - ../:/workspaces/{{cookiecutter.project_slug}}:cached
    command: sleep infinity
{% if "nats" in cookiecutter.app_type %}
    environment:
      - NATS_URL=nats://{{cookiecutter.project_slug}}-${USER}-nats-py{{cookiecutter.python_version.replace('.','')}}:4222
{% endif %}
    env_file:
      - ./devcontainer.env
    networks:
      - {{cookiecutter.project_slug}}-network
{% if "nats" in cookiecutter.app_type %}
  nats-{{cookiecutter.project_slug}}:
    image: nats:latest
    container_name: {{cookiecutter.project_slug}}-${USER}-nats-py{{cookiecutter.python_version.replace('.','')}}
    # ports:
      # - "${PORT_PREFIX}4222:4222"
      # - "${PORT_PREFIX}9222:9222"
    volumes:
      - ./nats_server.conf:/etc/nats/server.conf
    command: [ "--config", "/etc/nats/server.conf" ]
    env_file:
      - ./devcontainer.env
    networks:
      - {{cookiecutter.project_slug}}-network
{% endif %}
networks:
  {{cookiecutter.project_slug}}-network:
    name: {{cookiecutter.project_slug}}-${USER}-network
